require("foxtrottwist.plugins-setup")
require("foxtrottwist.core.options")
require("foxtrottwist.core.keymaps")
require("foxtrottwist.core.colorscheme")
require("foxtrottwist.plugins.treesitter")
require("foxtrottwist.plugins.lsp.lspsaga")
require("foxtrottwist.plugins.lsp.lspconfig")
require("foxtrottwist.plugins.lsp.null-ls")
require("foxtrottwist.plugins.nvim-cmp")
require("foxtrottwist.plugins.autopairs")
require("foxtrottwist.plugins.nvim-tree")
require("foxtrottwist.plugins.telescope")
require("foxtrottwist.plugins.oil")
require("foxtrottwist.plugins.alpha")
-- require("foxtrottwist.plugins.noice")
